dogodki_core/urls.py
"""dogodki_django URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
	https://docs.djangoproject.com/en/2.1/topics/http/urls/
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from dogodki_core import settings
import dogodki_app.views

urlpatterns = [
	path("", dogodki_app.views.DashboardView.as_view(), name="dashboard"),
	path("dogodek/ustvari", dogodki_app.views.UstvariDogodekView.as_view(), name="ustvari_dogodek"),
	path("dogodek/<int:pk>", dogodki_app.views.DogodekView.as_view(), name="dogodek"),
	path("dogodek/<int:pk>/uredi", dogodki_app.views.UrediDogodekView.as_view(), name="uredi_dogodek"),
	path("profil", dogodki_app.views.ProfilView.as_view(), name='profil'),
	path("dogodek/<int:pk>/prijava", dogodki_app.views.DogodekPrijavaView.as_view(), name="dogodek_prijava"),
	path("prijava", auth_views.LoginView.as_view(), name='login'),
    path("odjava", auth_views.LogoutView.as_view(), name='logout'),
	path('admin/', admin.site.urls),
	path('', include('social_django.urls', namespace='social'))
]

if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		path('__debug__/', include(debug_toolbar.urls)),
	] + urlpatterns

dogodki_app/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.urls.base import reverse
from django.utils import timezone


# Create your models here.

class User(AbstractUser):
	oddelek = models.CharField(max_length=5, blank=True, null=True)
	fresh = models.BooleanField(default=True, blank=False, null=False)

	# def save(self, *args, **kwargs):
	#     self.fresh = False
	#     super().save(*args, **kwargs)

	def __str__(self):
		return self.first_name + " " + self.last_name


class Dogodek(models.Model):
	naslov = models.CharField(max_length=50)
	datum = models.DateField()
	cas_prijave = models.DateTimeField(default=timezone.now)
	rok_prijave = models.DateTimeField()
	opis = models.TextField(null=True, blank=True)

	@property
	def število_mest(self):
		# TODO: Optimizacija?
		return sum((skupina.število_mest for skupina in self.skupine.all()))

	@property
	def število_navoljo(self):
		# TODO: Optimizacija?
		return self.število_mest - sum((skupina.prijavljeni.count() for skupina in self.skupine.all()))

	class Meta:
		verbose_name = "Dogodek"
		verbose_name_plural = "Dogodki"

	def __str__(self):
		return self.naslov

	def get_absolute_url(self):
		return reverse("dogodek", kwargs={"pk": self.pk})


class Skupina(models.Model):
	naslov = models.CharField(max_length=50)
	opis = models.TextField(null=True, blank=True)
	število_mest = models.PositiveIntegerField(validators=[MinValueValidator(1)])

	dogodek = models.ForeignKey(Dogodek, on_delete=models.CASCADE, related_name="skupine")

	class Meta:
		verbose_name = "Skupina"
		verbose_name_plural = "Skupine"

	def __str__(self):
		return "%s: %s" % (self.dogodek, self.naslov)


class Povabilo(models.Model):
	uporabnik = models.ForeignKey(User, on_delete=models.CASCADE)
	skupina = models.ForeignKey(Skupina, blank=True, null=True, related_name="prijavljeni", on_delete=models.CASCADE)
	dogodek = models.ForeignKey(Dogodek, on_delete=models.CASCADE, related_name="povabljeni")
	email_poslan = models.BooleanField(default=False)

	def clean(self):
		if self.skupina:
			prijavljeni = self.skupina.prijavljeni.filter(uporabnik__oddelek=self.uporabnik.oddelek).count()
			if prijavljeni >= self.skupina.število_mest:
				raise ValidationError("Vsa mesta so zasedena")

	class Meta:
		verbose_name = "Povabilo"
		verbose_name_plural = "Povabila"

	def __str__(self):
		return "%s: %s (%s)" % (self.dogodek, self.uporabnik, self.skupina)


class Obvestilo(models.Model):
	naslov = models.CharField(max_length=60)
	skupine = models.ManyToManyField(Skupina)
	vsebina = models.TextField(blank=True, null=True)
	email_poslan = models.BooleanField(default=False)

	class Meta:
		verbose_name = "Obvestilo"
		verbose_name_plural = "Obvestila"

	def __str__(self):
		return f"{self.naslov}"

dogodki_app/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.utils import timezone

from dogodki_app import models


class DogodekPrijavaForm(ModelForm):

    def clean(self):
        if self.instance.dogodek.rok_prijave < timezone.now():
            raise ValidationError("Rok za prijavo je potekel!")

        return super().clean()

    class Meta:
        model = models.Povabilo
        exclude = ("uporabnik", "dogodek")

dogodki_app/views.py
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.views.decorators.vary import vary_on_cookie
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.forms import inlineformset_factory, modelform_factory, ModelForm, ValidationError
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.utils import timezone

from datetime import date

from . import models
from .forms import DogodekPrijavaForm
from .util import FormsetMixin


# Create your views here.

class ProfilView(DetailView):
	template_name = "dogodki/profil.html"

	def get_object(self, **kwargs):
		return self.request.user


@method_decorator(vary_on_cookie, name="dispatch")
class DashboardView(LoginRequiredMixin, TemplateView):
	template_name = "dogodki/dashboard.html"

	def get_context_data(self):
		povabila = models.Povabilo.objects.filter(uporabnik=self.request.user)
		# Spodnje zahteva PostgreSQL!
		if self.request.user.is_staff:
			povabila = models.Povabilo.objects.distinct("dogodek")
		# Možna alternativa? https://stackoverflow.com/a/49291760
		danes = date.today()
		return {
			"odprta_povabila": povabila.filter(dogodek__datum__gte=danes),
			"pretekla_povabila": povabila.filter(dogodek__datum__lt=danes)
		}


@method_decorator(vary_on_cookie, name="dispatch")
class DogodekView(LoginRequiredMixin, DetailView):
	template_name = "dogodki/dogodek.html"
	model = models.Dogodek

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)

		try:
			context["povabilo"] = models.Povabilo.objects.get(dogodek=self.object, uporabnik=self.request.user)
		except:
			if not self.request.user.is_staff:
				raise PermissionDenied()

		obj_skupine = []
		found = False
		for skupina in self.object.skupine.all():
			prijavljeni = skupina.prijavljeni.filter(uporabnik__oddelek=self.request.user.oddelek).all()

			obj_skupina = {
				"pk": skupina.pk,
				"opis": skupina.opis,
				"naslov": skupina.naslov,
				"število_mest": skupina.število_mest,
				"število_prijavljenih": prijavljeni.count(),
				"prijavljeni": [],
				"moja": False
			}

			obj_skupina["polna"] = obj_skupina["število_mest"] - obj_skupina["število_prijavljenih"] < 1

			for prijava in prijavljeni:
				obj_prijava = {
					"uporabnik": prijava.uporabnik,
					"jaz": False
				}

				if not found and prijava.uporabnik == self.request.user:
					obj_prijava["jaz"] = True
					obj_skupina["moja"] = True
					found = True

				obj_skupina["prijavljeni"].append(obj_prijava)

			obj_skupine.append(obj_skupina)

		context["skupine"] = obj_skupine
		context["odprto"] = "povabilo" in context and context["povabilo"].dogodek.cas_prijave > timezone.now()
		context["poteklo"] = "povabilo" in context and context["povabilo"].dogodek.rok_prijave < timezone.now()

		context["zaprto"] = context["odprto"] or context["poteklo"]

		return context


class EditDogodekMixin(FormsetMixin, PermissionRequiredMixin):
	template_name = "dogodki/dogodek_edit.html"
	model = models.Dogodek

	form_class = modelform_factory(models.Dogodek, exclude=())
	formset_class = inlineformset_factory(models.Dogodek, models.Skupina, exclude=(), extra=0, min_num=1)


class UstvariDogodekView(EditDogodekMixin, CreateView):
	permission_required = "dogodek.can_create"


class UrediDogodekView(EditDogodekMixin, UpdateView):
	permission_required = "dogodek.can_create"


class DogodekPrijavaView(LoginRequiredMixin, UpdateView):
	form_class = DogodekPrijavaForm

	def get_object(self):
		return models.Povabilo.objects.get(dogodek__pk=self.kwargs["pk"], uporabnik=self.request.user.pk)

	def get_success_url(self):
		return self.object.dogodek.get_absolute_url()

	def form_invalid(self, form):
		for error in form.errors.values():
			messages.add_message(self.request, messages.ERROR, error.as_text())
		return redirect(self.object.dogodek.get_absolute_url())

dogodki_app/templates/bootstrap_messages.html
{% if messages %}
	<aside class="messages">
		{% for message in messages %}
			<div class="alert alert-danger {{ message.tags }}" role="alert">
				{{ message }}
			</div>
		{% endfor %}
	</aside>
{% endif %}

dogodki_app/templates/dogodki/admin/dogodek.html
{% extends "admin/change_form.html" %}
{% load i18n admin_static admin_urls %}

{% block object-tools-items %}
<li>
	<a href="{% url "admin:dogodki_app_povabilo_changelist" %}?dogodek__id__exact={{ object_id }}"><b>Seznam</b></a>
</li>
<li>
	<a href="{% url "admin:dogodki_app_povabi_oddelek" pk=object_id %}"><b>Povabi oddelke</b></a>
</li>
{{ block.super }}
{% endblock %}

dogodki_app/templates/dogodki/admin/dogodek_povabi_oddelke.html
{% extends "admin/import_export/base.html" %}
{% load i18n admin_urls static %}

{% block breadcrumbs_last %}
<a href="../change/">{{ dogodek }}</a> › Povabi oddelke
{% endblock %}

{% block content %}
<h1>Povabi oddelke</h1>
<p>Vsi uporabniki iz izbranih oddelkov bodo povabljeni na dogodek. Če so po e-pošti povabilo že prejeli, ga ne bodo dobili še enkrat!</p>

<form method="POST" action="">
	{% csrf_token %}

	<div class="form-row">
		<label for="id_oddelki">Oddelki:</label>
		{{ form.oddelki }}
	</div>

	<div class="submit-row">
		<input type="submit" class="default" value="{% trans "Submit" %}">
	</div>
</form>
{% endblock %}

dogodki_app/templates/dogodki/base.html
<!DOCTYPE html>
<html lang="sl">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	
	<title>{% block title %}SERŠ ŠVZ portal{% endblock title %}</title>

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<!-- FontAwesome 5 -->
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" integrity="sha384-kW+oWsYx3YpxvjtZjFXqazFpA7UP/MbiY4jvs+RWZo2+N94PFZ36T6TFkc9O3qoB" crossorigin="anonymous"></script>

</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container">
			<a class="navbar-brand" href="{% url 'dashboard' %}">SERŠ prijava na dogodke</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-nav" aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="main-nav">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'dashboard' %}"><i class="fas fa-home"></i> Domov</a>
					</li>
{% if request.user.is_staff %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'ustvari_dogodek' %}"><i class="fas fa-plus-circle"></i> Ustvari dogodek</a>
					</li>
{% endif %}
				</ul>
				<ul class="navbar-nav">
{% if request.user.is_authenticated %}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="" id="user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user"></i> {{ request.user.username }}</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
							<a class="dropdown-item" href="{% url 'profil' %}"><i class="fas fa-user"></i> Profil</a>
{% if request.user.is_staff %}
							<a class="dropdown-item text-danger" href="{% url 'admin:index' %}"><i class="fas fa-wrench"></i> Administracija</a>
{% endif %}
							<a class="dropdown-item text-danger" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Odjava</a>
						</div>
					</li>
{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i> Prijava</a>
					</li>
{% endif %}
				</ul>
			</div>
		</div>
	</nav>

	<main class="container mt-4">
		{% include "bootstrap_messages.html" %}
		{% block main %}{% endblock main %}
	</main>

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

dogodki_app/templates/dogodki/dashboard.html
{% extends 'dogodki/base.html' %}
{% block main %}
<div class="row">
	<div class="col-sm">
		<div class="card">
			<div class="card-header"><i class="far fa-clock"></i> Odprti dogodki</div>
			<div class="list-group list-group-flush">
			{% for povabilo in odprta_povabila %}
				<a href="{{ povabilo.dogodek.get_absolute_url }}" class="list-group-item list-group-item-action">
					<h5 class="mb-1">{{ povabilo.dogodek.naslov }}</h5>
					<small><i class="far fa-calendar-alt"></i> {{ povabilo.dogodek.datum }}</small>
					<small class="text-{{ povabilo.skupina|yesno:"success,danger"}}"><i class="fas fa-list"></i> {{ povabilo.skupina.naslov|default:"Niste še prijavljeni!" }}</small>
				</a>
			{% endfor %}
			</div>
		</div>
	</div>
	<div class="col-sm">
		<div class="card">
			<div class="card-header"><i class="far fa-calendar-alt"></i> Pretekli dogodki</div>
			<div class="list-group list-group-flush">
				{% for povabilo in pretekla_povabila %}
				<a href="{{ povabilo.dogodek.get_absolute_url }}" class="list-group-item list-group-item-action">
					<h5 class="mb-1">{{ povabilo.dogodek.naslov }}</h5>
					<small><i class="far fa-calendar-alt"></i> {{ povabilo.dogodek.datum }}</small>
					<small{% if not povabilo.skupina%} class="text-danger"{% endif %}><i class="fas fa-list"></i> {{ povabilo.skupina.naslov|default:"Niste se prijavili!" }}</small>
					{% if povabilo.opravljen %}
					<small class="text-danger"><i class="far fa-check-square"></i> opravljeno</small>
					{% else %}
					<small class="text-danger"><i class="fas fa-exclamation-triangle"></i> ni opravljeno</small>
					{% endif %}
				</a>
				{% endfor %}{% comment %}
				<a href="#" class="list-group-item">
					<h5 class="mb-1">Pokaži več...</h5>
				</a>{% endcomment %}
			</div>
		</div>
	</div>
</div>
{% endblock main %}

dogodki_app/templates/dogodki/dogodek.html
{% extends 'dogodki/base.html' %}
{% block title %}{{ dogodek.naslov }} · {{ block.super }}{% endblock title %}
{% block main %}
<div class="card mb-3">
	<div class="card-header">
		<i class="fas fa-info-circle"></i> Podatki o dogodku
{% if user.is_staff %}
		<a href="{% url "admin:dogodki_app_dogodek_change" dogodek.pk %}" class="btn btn-danger btn-sm float-right ml-2"><i class="fas fa-edit"></i> Administracija</a>
		<a href="{% url "uredi_dogodek" dogodek.pk %}" class="btn btn-primary btn-sm float-right"><i class="fas fa-edit"></i> Uredi</a>
{% endif %}
	</div>
	<div class="card-body row">
		<div class="col-md-7">
			<h3>{{ dogodek.naslov }}</h3>
			<p class="mb-0">{{ dogodek.opis }}</p>
		</div>
		<div class="col-md-5">
			<div{% if odprto %} class="text-danger"{% endif %}><i class="far fa-calendar-alt"></i> Začetek prijave: {{ dogodek.cas_prijave }}</div>
			<div{% if poteklo %} class="text-danger"{% endif %}><i class="far fa-calendar-alt"></i> Rok prijave: {{ dogodek.rok_prijave }}</div>
			<div><i class="fas fa-list"></i> {{ dogodek.skupine.count }} {{ dogodek.skupine.count | pluralize:"skupina,skupin" }}</div> <!-- TODO: pluralize_pl -->
			<div><i class="fas fa-users"></i> {{ dogodek.število_mest }} mest, {{ dogodek.število_navoljo }} na voljo</div>
			<div class="text-{{ povabilo.skupina|yesno:"success,danger"}}"><i class="fas fa-list"></i> Skupina: {{ povabilo.skupina.naslov|default:"niste še prijavljeni!" }}</div>
		</div>
	</div>
</div>

<form method="POST" action="{% url 'dogodek_prijava' dogodek.pk %}" class="card-columns">
{% csrf_token %}
{% for skupina in skupine %}
	<div class="card {% if skupina.moja %} border-success{% endif %}">
		<div class="card-header justify-content-between">
			<div class="{% if skupina.polna %}text-danger{% endif %}{% if skupina.moja %}text-success{% endif %}">
				<i class="fas fa-users"></i> {{ skupina.naslov }} 
				<span class="badge float-right badge-{{ skupina.polna|yesno:"danger,primary" }}">{{ skupina.število_prijavljenih }} / {{ skupina.število_mest }}</span>
			</div>
			{% if skupina.opis %}
			<small class="card-body p-0">
				<p class="card-text mt-2">
					{{ skupina.opis }}
				</p>
			</small>
			{% endif %}
		</div>
		<ul class="list-group list-group-flush">
	{% for prijava in skupina.prijavljeni %}
		{% if not zaprto and prijava.jaz %}
			<li class="list-group-item list-group-item-success d-flex justify-content-between">
				{{ prijava.uporabnik }}
				<button type="submit" name="skupina" value="" class="btn btn-sm btn-danger">Odjava</button>
			</li>
		{% else %}
			<li class="list-group-item list-group-item-light">{{ prijava.uporabnik }}</li>
		{% endif %}
	{% endfor %}
	{% if not skupina.moja %}
		{% if skupina.polna %}
			<li class="list-group-item list-group-item-light small bg-light text-danger">Ni več prostih mest!</li>
		{% elif not zaprto and povabilo and not povabilo.skupina %}
			<li class="list-group-item bg-light">
				<button type="submit" name="skupina" value="{{ skupina.pk }}" class="btn btn-block btn-primary">Prijava</button>
			</li>
		{% endif %}
	{% endif %}
		</ul>
	</div>
{% endfor %}
</form>
{% endblock main %}

dogodki_app/templates/dogodki/dogodek_edit.html
{% extends 'dogodki/base.html' %}
{% block title %}{{ form.naslov.value|default:"Nov dogodek" }} · urejanje · {{ block.super }}{% endblock title %}
{% block main %}
<form action="" method="POST" class="row">
{{ formset.management_form }}
	{% csrf_token %}
	<div class="col-md">
		<div class="card mb-3">
			<div class="card-header"><i class="far fa-clock"></i> Ustvari dogodek</div>
			<div class="card-body">
{% for error in form.non_field_errors %}
				<div class="alert alert-danger">
					{{ error|escape }}
				</div>
{% endfor %}
{% for field in form %}{% for error in field.errors %}
				<div class="alert alert-danger">
					<strong>{{ field.name }} </strong> - {{ error|escape }}
				</div>
{% endfor %}{% endfor %}

				<div class="form-group row">
					<label for="naslov" class="col-sm-3 col-form-label" required>Naslov:</label>
					<div class="col-sm">
						<input type="text" class="form-control" name="naslov" value="{{ form.naslov.value|default:"" }}" required>
					</div>
				</div>
				<div class="form-group row">
					<label for="datum" class="col-sm-3 col-form-label">Datum:</label>
					<div class="col-sm">
						<input type="date" class="form-control" name="datum" value="{{ form.datum.value|date:"Y-m-d"|default:"" }}" required>
					</div>
				</div>
				<div class="form-group row">
					<label for="rok_prijave" class="col-sm-3 col-form-label">Rok prijave:</label>
					<div class="col-sm">
						<input type="date" class="form-control" name="rok_prijave" value="{{ form.rok_prijave.value|date:"Y-m-d"|default:"" }}" required>
					</div>
				</div>
				<div class="form-group" style="margin: 0 -15px">
					<label for="opis" class="col-sm-3 col-form-label">Opis:</label>
					<div class="col-sm">
						<textarea class="form-control" name="opis">{{ form.opis.value|default:"" }}</textarea>
					</div>
				</div>
				<button type="submit" class="btn btn-primary mt-4 float-right"><i class="fas fa-save"></i> Shrani</button>
			</div>
		</div>

		<div class="card">
			<div class="card-header"><i class="far fa-clipboard"></i> Povabljeni</div>
			<ul class="list-group list-group-flush">
			<div class="card-body">
				<p class="card-text">Povabila lahko upravljate v <a href="{% url "admin:dogodki_app_povabilo_changelist" %}?dogodek__id__exact={{ object.pk }}">administratorskem vmesniku</a>.</p>
			</div>
{% comment %} {% for povabilo in dogodek.povabljeni.all %}
				<li class="list-group-item d-flex justify-content-between">
					Miha Frangež, 4. ag
					<button type="button" class="btn btn-sm btn-danger"><i class="fas fa-times"></i></button>
				</li>
			</ul>
{% endfor %} {% endcomment %}
		</div>
	</div>

	<div class="col-md">
		<h3>Skupine</h3>
{% for skupina in formset %}{% with counter=forloop.counter0 %}
{% include "dogodki/skupina_form.html" %}
{% endwith %}{% endfor %}
		<button type="button" class="btn btn-lg btn-block mt-3 btn-light" id="nova-skupina"><i class="fas fa-plus"></i></button>
	</div>
</form>

<script>
window.onload = () => {
	$("#nova-skupina").click(evt => {
		let counter = parseInt($("#id_skupine-TOTAL_FORMS").val());
{% with "${counter}" as counter %}
		let template = `{% include "dogodki/skupina_form.html" %}`;
{% endwith %}
		$(template).insertBefore("#nova-skupina");

		$("#id_skupine-TOTAL_FORMS").val(counter + 1);
	});
};
</script>
{% endblock main %}

dogodki_app/templates/dogodki/import.html
{% extends "admin/import_export/import.html" %}
{% load i18n %}
{% load admin_urls %}
{% load import_export_tags %}
{% load static %}

{% block content %}
<h2>Navodila za uporabo: </h2>
<h3>Opozorilo:</h3>
<p>
	Zaradi nezanesljivosti bralnikov datoteke <code>xlsx</code> (Microsoft Excel) niso podprte. <b>Trenutno je podprt samo format <code>xls</code> (Microsoft Excel 2003).</b>
</p>
<h3>Priprava datoteke</h3>
<p>
	eAsistent podatke izvaža v nestandardnem formatu, zato jih je pred uvozom potrebno pripraviti:
	<ol>
		<li>Prenešeno datoteko iz eAsistenta odprite v programu za urejanje preglednic (npr. Microsoft Excel)</li>
		<li><i>Izbrišite eAsistent logotip</i></li>
		<li>Izbrišite celotno prvo (prazno) vrstico</li>
		<li>Datoteko shranite v enem izmed podprtih formatov</li>
	</ol>
</p>

<h3>Uvoz:</h3>
<p>
	Izberite datoteko za uvoz, v spustnem meniju izberite ustrezen format in kliknite gumb "Submit".
</p>
<p>
	Ko se vam prikaže tabela preverite, če so podatki pravilni. Ko ste v to prepričani, uvoz potrdite z gumbom "Confirm import".
</p>
<hr>
<br>
{{ block.super }}
{% endblock %}

dogodki_app/templates/dogodki/profil.html
{% extends 'dogodki/base.html' %}
{% block title %}Profil · {{ block.super }}{% endblock title %}
{% load static %}
{% block main %}
<div class="row justify-content-center">
	<div class="col-md-6">
		<div class="card m-auto">
			<div class="card-header"><i class="far fa-address-card"></i> Podatki o uporabniku</div>
			<div class="card-body">
				<div class="row">
					<dl class="col">
						<dt>Ime:</dt>
						<dd>{{ user.first_name }}</dd>
						<dt>Priimek:</dt>
						<dd>{{ user.last_name }}</dd>
						<dt>Oddelek:</dt>
						<dd>{{ user.oddelek }}</dd>
					</dl>
					<dl class="col">
						<dt>Uporabniško ime:</dt>
						<dd>{{ user.username }}</dd>
						<dt>E-poštni naslov:</dt>
						<dd>{{ user.email }}</dd>
					</dl>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock main %}

dogodki_app/templates/dogodki/skupina_form.html
{% for field in skupina.hidden_fields %}
	{{ field }}
{% endfor %}
<div class="card mb-3 skupina" id="skupina-{{ counter }}">
	<div class="card-header form-inline">
		<i class="fas fa-users"></i> <input type="text" class="form-control-plaintext ml-1 p-0" name="skupine-{{ counter }}-naslov" style="width: auto;" value="{{ skupina.naslov.value|default:"" }}" placeholder="Naslov" required>
	</div>
	<div class="card-body">
		<span class="text-danger">{{ skupina.naslov.število_mest }}</span>
		<div class="form-group row">
			<label for="skupine-{{ counter }}-število_mest" class="col-sm-3 col-form-label">Število mest:</label>
			<div class="col-sm">
				<input type="number" class="form-control" name="skupine-{{ counter }}-število_mest" min=1 value="{{ skupina.število_mest.value|default:"" }}" required>
			</div>
			<span class="text-danger">{{ skupina.errors.število_mest }}</span>
		</div>
		<div class="form-group" style="margin: 0 -15px">
			<label for="skupine-{{ counter }}-opis" class="col-sm-3 col-form-label">Opis:</label>
			<div class="col-sm">
				<textarea class="form-control" name="skupine-{{ counter }}-opis">{{ skupina.opis.value|default:"" }}</textarea>
			</div>
			<span class="text-danger">{{ skupina.errors.opis }}</span>
		</div>
	</div>
</div>